# Generated by Django 2.1.3 on 2018-12-15 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0006_auto_20181214_1913'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Guest',
        ),
    ]
