# Generated by Django 2.1.3 on 2018-12-16 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0007_auto_20181215_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='guest',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
